version: "2.3"
services:
  Lynx_BOT:
    cpus: 4
    mem_limit: "20g"
    image: ghcr.io/lynx-chess/lynx-bot:latest
    volumes:
      - ./lynx_bot-config.yml:/lynx_bot/configtmp.yml
      - ./lichess-bot-logs:/lynx_bot/log
      - ./lynx-logs:/lynx/logs
    working_dir: /lynx_bot
    restart: always
    command:
      - sh
      - -c
      - |
        sed "s/LICHESS_API_TOKEN/${LICHESS_API_TOKEN}/" configtmp.yml > config.yml
        . .venv/bin/activate
        python3 lichess-bot.py
