token: "LICHESS_API_TOKEN"  # Lichess OAuth2 Token
url: "https://lichess.org/" # Lichess base URL

engine:                     # Engine settings
  dir: "/lynx"              # Dir containing engines
  working_dir: ""                  # Directory where the chess engine will read and write files. If blank or missing, the current directory is used.
                                   # NOTE: If working_dir is set, the engine will look for files and directories relative to this directory, not where lichess-bot was launched. Absolute paths are unaffected.
  name: "Lynx"              # Binary name of the engine to use
  protocol: "uci"
  ponder: false
  polyglot:
    enabled: false           # Activate polyglot book.
    selection: "weighted_random" # Move selection is one of "weighted_random", "uniform_random" or "best_move" (but not below the min_weight in the 2nd and 3rd case).
    max_depth: 8             # Half move max depth
    book:
      standard:              # List of book file paths for variant standard.
        - engines/book1.bin
        - engines/book2.bin
# #     atomic:                # List of book file paths for variant atomic.
# #       - engines/atomicbook1.bin
# #       - engines/atomicbook2.bin
# #     etc.
# #     Use the same pattern for 'giveaway' (antichess), 'crazyhouse', 'horde', 'kingofthehill', 'racingkings' and '3check' as well.
#     min_weight: 1            # Does not select moves with weight below min_weight (min 0, max: 65535).
    # selection: "weighted_random"   # Move selection is one of "weighted_random", "uniform_random" or "best_move" (but not below the min_weight in the 2nd and 3rd case).
    # max_depth: 20                  # How many moves from the start to take from the book.

  draw_or_resign:
    resign_enabled: false
    # resign_score: -1000      # If the score is less than or equal to this value, the bot resigns (in cp).
    # resign_for_egtb_minus_two: true # If true the bot will resign in positions where the online_egtb returns a wdl of -2.
    # resign_moves: 3          # How many moves in a row the score has to be below the resign value.
    offer_draw_enabled: false
    # offer_draw_score: 0      # If the absolute value of the score is less than or equal to this value, the bot offers/accepts draw (in cp).
    # offer_draw_for_egtb_zero: true # If true the bot will offer/accept draw in positions where the online_egtb returns a wdl of 0.
    # offer_draw_moves: 5      # How many moves in a row the absolute value of the score has to be below the draw value.
    # offer_draw_pieces: 10    # Only if the pieces on board are less than or equal to this value, the bot offers/accepts draw.

  online_moves:
    max_depth: 8 # The maximum number of moves a bot can make in the opening before it stops consulting the online opening books. If max_depth is 5, then the bot will stop consulting the online books after its fifth move
    max_out_of_book_moves: 4 # Stop using online opening books after they don't have a move for 'max_out_of_book_moves' positions. Doesn't apply to the online endgame tablebases.
    max_retries: 2           # The maximum amount of retries when getting an online move.
    chessdb_book:
      enabled: false
      min_time: 20
      move_quality: "good"   # One of "all", "good", "best".
      min_depth: 20          # Only for move_quality: "best".
      contribute: false
    lichess_cloud_analysis:
      enabled: true
      min_time: 55
      move_quality: "good"   # One of "good", "best".
      max_score_difference: 50 # Only for move_quality: "good". The maximum score difference (in cp) between the best move and the other moves.
      min_depth: 20
      min_knodes: 0
    lichess_opening_explorer:
      enabled: false
      min_time: 55
      move_quality: "good"
      source: "lichess"            # One of "lichess", "masters", "player"
      player_name: ""              # The lichess username. Leave empty for the bot's username to be used. Used only when source is "player".
      # sort: "winrate"              # One of "winrate", "games_played"
      min_games: 10                # Minimum number of times a move must have been played to be chosen.
    online_egtb:
      enabled: false
      min_time: 20
      max_pieces: 7
      source: "lichess"      # One of "lichess", "chessdb".
      move_quality: "best"   # One of "good", "best", "suggest" (it takes all the "good" moves and tells the engine to only consider these; will move instantly if there is only 1 "good" move).

  lichess_bot_tbs:           # The tablebases list here will be read by lichess-bot, not the engine.
    syzygy:
      enabled: false
      paths:
      # - "engines/syzygy"
      max_pieces: 7
      move_quality: "best"   # One of "good", "best", "suggest" (it takes all the "good" moves and tells the engine to only consider these; will move instantly if there is only 1 "good" move).
    gaviota:
      enabled: false
      paths:
      # - "engines/gaviota"
      max_pieces: 5
      min_dtm_to_consider_as_wdl_1: 120  # The minimum dtm to consider as syzygy wdl=1/-1. Set to 100 to disable.
      move_quality: "best"   # One of "good", "best", "suggest" (it takes all the "good" moves and tells the engine to only consider these; will move instantly if there is only 1 "good" move).


# engine_options:            # Any custom command line params to pass to the engine.
#   cpuct: 3.1

  homemade_options:
#   Hash: 256

#   uci_options:              # Arbitrary UCI options passed to the engine.
#     Move Overhead: 100      # Increase if your bot flags games too often.
#     Threads: 2              # Max CPU threads the engine can use.
#     Hash: 256               # Max memory (in megabytes) the engine can allocate.
#     SyzygyPath: "./syzygy/"  # Paths to Syzygy endgame tablebases
#   go_commands:              # Additional options to pass to the UCI go command.
#     nodes: 1                # Search so many nodes only.
#     depth: 5                # Search depth ply only.
#     movetime: 1000          # Integer. Search exactly movetime milliseconds.

  silence_stderr: false      # Some engines (yes you, Leela) are very noisy.

abort_time: 20              # Time to abort a game in seconds when there is no activity
fake_think_time: false      # Artificially slow down the bot to pretend like it's thinking
rate_limiting_delay: 0      # Time (in ms) to delay after sending a move to prevent "Too Many Requests" errors.
move_overhead: 1000         # Increase if your bot flags games too often.
pgn_directory: "game_records" # A directory where PGN-format records of the bot's games are kept
pgn_file_grouping: "all"      # How to group games into files. Options are "game", "opponent", and "all"
                                   # "game" (default) - every game is written to a different file named "{White name} vs. {Black name} - {lichess game ID}.pgn"
                                   # "opponent" - every game with a given opponent is written to a file named "{Bot name} games vs. {Opponent name}.pgn"
                                   # "all" - every game is written to a single file named "{Bot name} games.pgn"

challenge:                  # Incoming challenges
  concurrency: 5            # Number of games to play simultaneously
  sort_by: "first"          # Possible values: "best", "first"
  accept_bot: true          # Accepts challenges coming from other bots
  only_bot: false           # Accepts challenges by bots only
  max_increment: 30         # Maximum amount of increment to accept a challenge. the max is 180s. set to 0 for no increment
  min_increment: 0          # Minimum amount of increment to accept a challenge
  max_base: 5400            # Maximum amount of base time to accept a challenge. 1:30h
  min_base: 0               # Minimum amount of base time to accept a challenge. 0s
  # max_days: 14                     # Maximum number of days per move to accept a challenge for a correspondence game.
                                   # Unlimited games can be accepted by removing this field or specifying .inf
  # min_days: 1                      # Minimum number of days per move to accept a challenge for a correspondence game.
  variants:                 # Chess variants to accept (http://lichess.org/variant)
    - standard
    - fromPosition
#   - antichess
#   - atomic
#   - chess960
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  time_controls:            # time controls to accept
    - ultraBullet
    - bullet
    - blitz
    - rapid
    - classical
#     - correspondence
  modes:                    # game modes to accept
    - casual                # unrated games
    - rated                 # rated games - must comment if the engine doesn't try to win

  block_list:                # List of users from which the challenges are always declined
  # Stockfish clones/derivatives
    - ASliceOfPi
    - AVeryBigMistake
    - Africaata
    - AlexaGarry-BOT
    - Anand_bot
    - AnonymousBotter
    - BOT-Feline
    - BOT5431
    - BRAINLEARN11_NNUE
    - Bot_AOOP11
    - Bot_master_india
    - Botdefoin
    - Botkingteam33
    - Botyuliirma
    - Brabemachess-BOT
    - BufferUnderflow
    - CPU2002
    - CPU2006
    - CPU2010
    - CheemsChungusBOT
    - ChessBot2156
    - Chess_Champion12
    - CocopikachuBOT
    - CoderDen732
    - DaBestFARMER
    - EmanBot
    - EmanPureNN
    - Emptik-AI
    - Emptik-AI-2
    - EmptikBot
    - EmptikBot247
    - EmptikBotEman
    - EmptikVariantsBot
    - EslamFishV99
    - FantacticEman
    - Fast_Checkmate_ALL
    - FireChessX
    - FireFishBOT
    - FireFishBOT_v2
    - FishFingersMcGee
    - FlamingDragon_9000
    - FlixBot
    - HaBaGuBot
    - HackerChessBot
    - HansNiemannBot
    - HappyFarmer3000
    - HappyFarmerChallenge
    - HistoryExplorer
    - IA_Horus
    - Intron014
    - KQRBNPkqrbnp
    - Karpov_bot
    - KhalidOmar
    - KunkkaBot
    - LBOT007
    - LC0-Bot
    - Leela420
    - Leela8-Test
    - LeelaMultiPoss
    - Leelabotmaster
    - Lenya228_BOT
    - LiliGirlPlay
    - LioCT
    - LoseisnotAvailablehe
    - M-Z_Bot
    - M2-MY
    - MacUser60
    - Major-Maxy
    - Mate-AI
    - MateAI
    - MegaChessRBOT
    - Minchesterbot
    - Moment-That-Inspires
    - Mr-Chess-Berserk
    - MrChessTheBot
    - Mr_Chess_Berserk
    - MyNameIsLeela
    - Nam-stockfish
    - Nikitosik-ai
    - NikitosikVariantsbot
    - Nikitosikbot
    - Nikitosikbot_v2
    - Nitrik_asit
    - No-StockFish-Bots
    - Occhessadvanced
    - Official_bot
    - OpeningsBot
    - Perfect-Bot
    - PetersBot
    - ProjectHuman
    - ProteusSF
    - ProteusSF-Aureo
    - ProteusSF-Godot
    - ProteusSF-Open
    - ProteusSF-Turbo
    - ProteusSF-lite
    - ProteusSFX-AI
    - PurpleHunter
    - Puztel-bot
    - R4033
    - RaspFish
    - ReinforcementTrial
    - ResoluteBot
    - RipTorn
    - SOLIDOR59
    - ShashChessBot
    - ShashChess_MsP
    - Shineshou90_BOT
    - SkyBlaster
    - SolistaBot
    - Spectral-AI
    - Starfaith
    - Stark_Robot_super
    - StockFish16_2023
    - StockSergio
    - Stockfish-MEDIUM
    - StockfishPower
    - THE_STRONGEST_BOT
    - TasmanRevenge
    - TeamChelsie
    - Test_God_50_BOT
    - TheFreshman1902
    - TheFreshmanLc0
    - TheMatrix2025
    - TheMatrix2029
    - The_Devansh117
    - The_Stockfish_14_Pro
    - ThisIsntABot
    - TorBot
    - ToromBot
    - Try_To_Beat_Me_Kid
    - Ultron81
    - UnbalanceBot
    - Unreal-Chess
    - VariantTourneysBot
    - VariantsBot
    - VariantsONTop
    - Viet-AI
    - VishyNotAnand_TheBot
    - WillBoChessEngine
    - WoodStyleEngine
    - YoBot_v2
    - ZAXAZAXA
    - Zas_en_toda_la_boca
    - ararimbelami
    - beckapplebot
    - bird_xx
    - blue_lightningdragon
    - blundar_bot
    - bot_bigbrain
    - botteam-com
    - caissa-ai
    - caissa-test
    - caissa-x
    - chessbot2880
    - chesshyperbot
    - droidfish07
    - duythong1402
    - faith_bot
    - good_bot223344
    - imnotsohuman
    - isaac_terminator
    - kdpchess
    - libarychesscoffee
    - lord-bot
    - magnusglad_bot
    - mayhem23111
    - meomeous
    - micpilarBot_variants
    - micpilar_bot
    - opentalbot2023
    - pangubot
    - project-shashchess
    - que-encrypt
    - sora3-stockfish
    - stockfish12_Johan
    - ttBOT
    - uai-bot-sf-005
    - uai-bot-test-3
    - unrevealed-Bot
    - zlatana75
    - MateAI
    - duchessAI
    - thegamesknow
    - KunkkaPi
    - colinbot
    - JustLeela
    - preunpatching-bot
    - Gotterpufer
    - BlankasBot1
    - aliozendev
    - OlympusCz
    - OlympusEvolvedCz
    - BotAlex
    - BotAlex1N
    - Botalex2N
    - BotAlex3N
    - BotalexM
    - Botalexnc
    - BotalexCandidateM
    - BotAlexMI
    - BotAlexGrandMaster
    - TLE-OF-WATER
    - TheMatrix2025
    - TheMatrix2029
    - Matrix-AI
    - tomlesspit
    - European_Chess_Bot
    - NikoglayKlei25
    - EliteAY17_AIChess
    - XChessAY
    - ChessBotAY_AI
    - Nishythebot
    - Hufflewitzw
    - Kyreds_pet
    - Berserk12-X
    - CruelKen
    - Zoe_ChessBot
    - MalanChess
    - NewtSkamender
    - PETrSmirnovBOT
    - Timofei2506
    - Vatsal_1123_bot
    - Torch3
    - CVA728_BOT_1
    - SVC_3259
    - PlayOnPhoneOnly
    - NikoglayKlei25
    - ElNanonoeshumano33
    - HeckerBot
    - Hecker-AI
    - HeckerGPT
    - AnIndianAnand
    - Stockfish161Pro
    - Stockfish_13-1
    - StockfishPro-2025
    - Kyreds_pet
    - MironovKimChess_Bot
    - FireBot_PL
    - AlphaFish_Zero
    - LiveChess-F1ghter
    - Endogenetic-Bot
    - Vatsal_1123_bot
    - SacrificialSage
    - Q-Learning
    - doom-bot
    - MironovKimChess_Bot
    - MS-AI

  recent_bot_challenge_age: 60 # Maximum age of a bot challenge to be considered recent in seconds
  max_recent_bot_challenges: 2 # Maximum number of recent challenges that can be accepted from the same bot
  bullet_requires_increment: False # Require that bullet game challenges from bots have a non-zero increment

greeting:
  # Optional substitution keywords (include curly braces):
  #   {opponent} to insert opponent's name
  #   {me} to insert bot's name
  # Any other words in curly braces will be removed.
  hello: "Hey {opponent}, I'm {me}. gl! Type !help for supported commands" # Message to send to opponent chat at the start of a game
  goodbye: "gg" # Message to send to opponent chat at the end of a game
  hello_spectators: "Hey, I'm {me}. Type !help for supported commands" # Message to send to spectator chat at the start of a game
  goodbye_spectators: "Thx for watching!" # Message to send to spectator chat at the end of a game

matchmaking:
  allow_matchmaking: true     # Set it to 'true' to challenge other bots.
  allow_during_games: true    # Set it to 'true' to create challenges during long games.
  challenge_variant: "standard" # If set to 'random', the bot will choose one variant from the variants enabled in 'challenge.variants'.
  challenge_timeout: 1        # Create a challenge after being idle for 'challenge_timeout' minutes. The minimum is 1 minute.
  challenge_initial_time:     # Initial time in seconds of the challenge (to be chosen at random).
    - 60                                # 60 + 1
  challenge_increment:        # Increment in seconds of the challenge (to be chosen at random).
    - 1

  opponent_min_rating: 2200             # Opponents rating should be above this value (600 is the minimum rating in lichess).
  opponent_max_rating: 2900             # Opponents rating should be below this value (4000 is the maximum rating in lichess).
  # opponent_rating_difference: 500     # The maximum difference in rating between the bot's rating and opponent's rating.
  opponent_allow_tos_violation: false   # Set to 'false' to prevent challenging bots that violated Lichess Terms of Service.
  challenge_mode: "rated"               # Set it to the mode in which challenges are sent. Possible options are 'casual', 'rated' and 'random'.
  challenge_filter: fine                # If a bot declines a challenge, do not issue a similar challenge to that bot. Possible options are 'none', 'coarse', and 'fine'.
  include_challenge_block_list: true    # Do not challenge bots in the challenge: block_list in addition to the matchmaking block list.
  overrides:                            # List of overrides for the matchmaking specifications above. When a challenge is created, either the default specification above or one of the overrides will be randomly chosen.
    classical:                          #   Name of the override. Can be anything as long as each override has a unique name ("bullet_only_horde" and "easy_chess960" in these examples).
      challenge_initial_time:
        - 1200                          # 20 + 8
      challenge_increment:
        - 8
      opponent_min_rating: 2000         # Classical ratings are significatevely lower than bullet/blitz/rapid ones
      opponent_max_rating: 2800
    rapid:                              # 5 + 5
      challenge_initial_time:
        - 300
      challenge_increment:
        - 5
    blitz:                              # 3 + 2
      challenge_initial_time:
        - 180
      challenge_increment:
        - 2
    # bullet:   # Included in the main specification
    #   challenge_initial_time:
    #     - 60
    #   challenge_increment:
    #     - 1

  block_list:                 # The list of bots that will not be challenged
  # include_challenge_block_list is set to true, so we can have this empty
  # Don't want to receive challenges
    - openingsexercise
    - turochamp-1ply
    - turochamp-2ply
